import pandas as pd
from mjtracker import apply_mj, mj, interface_to_official_lib


def test_mj_libs():
    columns = [
        "candidate_id",
        "intention_mention_1",
        "intention_mention_2",
        "intention_mention_3",
        "intention_mention_4",
        "intention_mention_5",
        "intention_mention_6",
        "intention_mention_7",
        "poll_type_id",
        "population",
        "poll_id",
        "poll_type",
        "nb_people",
        "start_date",
        "end_date",
        "folder",
        "population",
        "id",
        "institut",
        "commanditaire",
        "mention1",
        "mention2",
        "mention3",
        "mention4",
        "mention5",
        "mention6",
        "mention7",
        "nombre_mentions",
        "question",
        "name",
        "surname",
        "parti",
        "annonce_candidature",
        "retrait_candidature",
        "second_round",
        "candidate",
    ]
    first_row = [
        "PhilippeYo",
        9,
        9,
        12,
        10,
        10,
        10,
        10,
        1,
        "all",
        1,
        "Presidentielle",
        1000,
        "2022-01-01",
        "2022-01-02",
        "folder",
        "all",
        1,
        "institut",
        "commanditaire",
        "mention1",
        "mention2",
        "mention3",
        "mention4",
        "mention5",
        "mention6",
        "mention7",
        7,
        "question",
        "Philippe",
        "Yo",
        "parti",
        "2022-01-01",
        "2022-01-02",
        "2022-01-03",
        "Philippe Yo",
    ]
    second_row = [
        "EvaYeah",
        11,
        11,
        8,
        10,
        10,
        10,
        10,
        1,
        "all",
        1,
        "Presidentielle",
        1000,
        "2022-01-01",
        "2022-01-02",
        "folder",
        "all",
        1,
        "institut",
        "commanditaire",
        "mention1",
        "mention2",
        "mention3",
        "mention4",
        "mention5",
        "mention6",
        "mention7",
        7,
        "question",
        "Eva",
        "Yeah",
        "parti",
        "2022-01-01",
        "2022-01-02",
        "2022-01-03",
        "Eva Yeah",
    ]

    df = pd.DataFrame([first_row, second_row], columns=columns)

    df = apply_mj(df, official_lib=False, reversed=True, rolling_mj=False)
    print(df)

    df = apply_mj(df, official_lib=True, reversed=True, rolling_mj=False)
    print(df)
